name: pre-commit

on:
  pull_request:
  push:
    branches:
      - dev_ovctech

jobs:
  lint:
    name: pre-commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pythonVersion: [11]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.${{ matrix.pythonVersion }}"
      - uses: pre-commit/action@v3.0.0
